homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include configurations/customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named configurations/themes/

# Enables configuration UI
config:

# Configures logging levels
logger:
  default: critical
  logs:
    homeassistant.components.http.ban: warning

http:
  api_password: !secret http_password
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history: !include configurations/components/history.yaml

# View all events in a logbook
logbook: !include configurations/components/logbook.yaml

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# MQTT Broker
#mqtt: !include configurations/components/mqtt.yaml
mqtt:
  broker: !secret mqtt_ip

# Open Weather Map integration
weather:
  - platform: openweathermap
    api_key: !secret open_weather_api
  
# IFTTT webhooks
ifttt: 
  key: !secret ifttt_key
  

# Folder containing automation rules
automation: !include_dir_merge_list configurations/automations
# Config file for device tracking entries
device_tracker: !include configurations/components/device_tracker.yaml
# Config file for defining groups
group: !include configurations/groups.yaml
# Philip Hue settings file
hue: !include configurations/components/hue.yaml
# InfluxDB setting file
influxdb: !include configurations/components/influxdb.yaml
# Config file for media players
media_player: !include configurations/components/media_player.yaml
# Notification services
notify: !include configurations/components/notify.yaml
# List of iFrames to add to the UI
panel_iframe: !include configurations/components/iframes.yaml
# Remotes
remote: !include configurations/components/remote.yaml
# Folder containing scripts
script: !include_dir_merge_named configurations/scripts
# Sensor entries and configurations
sensor: !include configurations/components/sensor.yaml
# List of shell commands
shell_command: !include configurations/components/shell_command.yaml
# Geographical zones
zone: !include_dir_merge_list configurations/zones